name: Release Docker Images for RC

on:
  push:
    branches:
      # FIXME: debug code
      # - rc/*
      - support/github-actions

jobs:

  build-rc:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Docker Buildx
      uses: crazy-max/ghaction-docker-buildx@v1.0.4

    - name: Login to docker.io registry
      run: |
        echo ${{ secrets. DOCKER_REGISTRY_PASSWORD }} | docker login --username wsmoogle --password-stdin

    - name: Build Docker Image
      run: |
        CACHE_REF=weseek/growi:3-cache
        docker buildx build \
          --tag growi \
          --platform linux/amd64 \
          --load \
          --cache-from=type=registry,ref=$CACHE_REF \
          --file ./docker/Dockerfile .

    - name: Get SemVer
      run: |
        semver=`npm run version --silent`
        echo ::set-env name=SEMVER::$(echo $semver)

    - name: Docker Tags by SemVer
      uses: weseek/ghaction-docker-tags-by-semver@v1.0.3
      with:
        source: growi
        target: weseek/growi
        semver: ${{ env.SEMVER }}
        publish: true
