name: Release Docker Images

on:
  push:
    tags:
      - v3.*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Bump version
      run: sh ./bin/github-actions/bump-version.sh

    - name: Set up Docker Buildx
      uses: crazy-max/ghaction-docker-buildx@v1.0.4
      with:
        # Buildx version. Example: v0.3.0
        version: # optional, default is latest

    - name: Build Docker Image
      run: |
        docker buildx build \
          --platform linux/amd64 \
          --output "type=image,push=false" \
          --file ./docker/Dockerfile .
