name: Release Docker Images for RC

on:
  push:
    branches:
      - rc/**


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:

  determine-tags:
    runs-on: ubuntu-latest

    outputs:
      TAGS: ${{ steps.meta.outputs.tags }}

    steps:
    - uses: actions/checkout@v4

    - name: Retrieve information from package.json
      uses: myrotvorets/info-from-package-json-action@v2.0.2
      id: package-json

    - name: Docker meta for docker.io
      uses: docker/metadata-action@v5
      id: meta
      with:
        images: docker.io/weseek/growi
        sep-tags: ','
        tags: |
          type=raw,value=${{ steps.package-json.outputs.packageVersion }}
          type=raw,value=${{ steps.package-json.outputs.packageVersion }}.{{sha}}


  build-image-rc:
    uses: weseek/growi/.github/workflows/reusable-app-build-image.yml@support/168264-node-v22
    with:
      image-name: weseek/growi
      tag-temporary: latest-rc
    secrets:
      AWS_ROLE_TO_ASSUME_FOR_OIDC: ${{ secrets.AWS_ROLE_TO_ASSUME_FOR_OIDC }}


  publish-image-rc:
    needs: [determine-tags, build-image-rc]

    uses: weseek/growi/.github/workflows/reusable-app-create-manifests.yml@support/168264-node-v22
    with:
      tags: ${{ needs.determine-tags.outputs.TAGS }}
      registry: docker.io
      image-name: weseek/growi
      tag-temporary: latest-rc
    secrets:
      DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

